platform :ios, :deployment_target => '8.0'
inhibit_all_warnings!
use_frameworks!

target 'BLList_Example' do
  pod 'BLList', :path => '../'

  target 'BLList_Tests' do
    inherit! :search_paths

  end
end
